
package My_Forms;


import My_Classes.Function_Class;
import My_Classes.Author;
import java.awt.Color;
import static java.awt.Color.gray;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.ScrollPaneLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhung
 */
public class ManageAuthorForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageGenresForm
     */
    
    My_Classes.Author author = new My_Classes.Author();
    
    
       public void displayImage_AuthorLogo(){
            
     ImageIcon imgIconTeam = new ImageIcon(getClass().getResource("/My_Images/AuthorImage.jpg"));
     Image image = imgIconTeam.getImage().getScaledInstance(jLabel_FormTitle.getWidth(), jLabel_FormTitle.getHeight(), Image.SCALE_SMOOTH);
    jLabel_FormTitle.setIcon(new ImageIcon(image));
      
     }
        
    
    
    public ManageAuthorForm() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
        
        displayImage_AuthorLogo();
            
        // add a gray border to the panel
         Border panelPlatformBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(51,51,51));
        jPanel_MGF.setBorder(panelPlatformBorder);
  
         
        
    
         //custom the jtable
         jTable_Genres.setSelectionBackground(new Color(204,255,255));
         jTable_Genres.setSelectionForeground(Color.black);
         jTable_Genres.setRowHeight(40);
         jTable_Genres.setShowGrid(true);
         jTable_Genres.setBackground(new Color(240,240,240));
         
        
           Border panelPlatform_C_Border = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(1,50,67));
         jPanel_Platform_C.setBorder(panelPlatform_C_Border);

         //cuztomize JtableHeader
         jTable_Genres.getTableHeader().setBackground(new Color(153,204,255));
         jTable_Genres.getTableHeader().setFont(new Font("Verdana",Font.BOLD,14));
         jTable_Genres.getTableHeader().setOpaque(false);
        
         
         //hide the jlabel "empty name message";
         jLabel_EnterFname.setVisible(false);
         jLabel_EnterLname.setVisible(false);
        
         //populate Jtable WIth Genres
         //populateJtableWIthGenres();
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel_MGF = new javax.swing.JPanel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jPanel_Platform_C = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Genres = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Empty_Firstname = new javax.swing.JTextField();
        jLabel_EnterFname = new javax.swing.JLabel();
        jTextField_Empty_LastName = new javax.swing.JTextField();
        jTextField_Expertise = new javax.swing.JTextField();
        jTextField_About = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_EnterLname = new javax.swing.JLabel();
        jButton_Edit = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jScrollPane2.setViewportView(jEditorPane1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_MGF.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_CloseForm.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_CloseForm.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("X");
        jLabel_CloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jPanel_Platform_C.setBackground(new java.awt.Color(51, 51, 51));

        jTable_Genres.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable_Genres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Genres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_GenresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Genres);

        javax.swing.GroupLayout jPanel_Platform_CLayout = new javax.swing.GroupLayout(jPanel_Platform_C);
        jPanel_Platform_C.setLayout(jPanel_Platform_CLayout);
        jPanel_Platform_CLayout.setHorizontalGroup(
            jPanel_Platform_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Platform_CLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_Platform_CLayout.setVerticalGroup(
            jPanel_Platform_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Platform_CLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));

        jLabel_Title.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("Manage Author");
        jLabel_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_FormTitle.setBackground(new java.awt.Color(1, 50, 67));
        jLabel_FormTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Title)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");

        jTextField_ID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });

        jTextField_Empty_Firstname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField_Empty_Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Empty_FirstnameActionPerformed(evt);
            }
        });

        jLabel_EnterFname.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_EnterFname.setForeground(new java.awt.Color(153, 204, 255));
        jLabel_EnterFname.setText("*enter the first name");
        jLabel_EnterFname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EnterFnameMouseClicked(evt);
            }
        });

        jTextField_Empty_LastName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField_Empty_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Empty_LastNameActionPerformed(evt);
            }
        });

        jTextField_Expertise.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField_Expertise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ExpertiseActionPerformed(evt);
            }
        });

        jTextField_About.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AboutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Expertise");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("About:");

        jLabel_EnterLname.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_EnterLname.setForeground(new java.awt.Color(153, 204, 255));
        jLabel_EnterLname.setText("*enter the last name");
        jLabel_EnterLname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EnterLnameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 270, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Expertise, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_About, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_EnterFname, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel_EnterLname, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField_Empty_LastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Empty_Firstname, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Empty_Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EnterFname)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Empty_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EnterLname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Expertise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_About, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MGFLayout = new javax.swing.GroupLayout(jPanel_MGF);
        jPanel_MGF.setLayout(jPanel_MGFLayout);
        jPanel_MGFLayout.setHorizontalGroup(
            jPanel_MGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MGFLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_MGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_MGFLayout.createSequentialGroup()
                        .addGroup(jPanel_MGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel_MGFLayout.createSequentialGroup()
                                .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jPanel_Platform_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_MGFLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel_MGFLayout.setVerticalGroup(
            jPanel_MGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MGFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel_MGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Platform_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_MGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add)
                    .addComponent(jButton_Edit)
                    .addComponent(jButton_Delete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_MGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_MGF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
      
        //close form
        this.dispose();
        
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jTextField_Empty_FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Empty_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Empty_FirstnameActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
       
       
        //Add a new author  
        String fname = jTextField_Empty_Firstname.getText(); 
           String lname = jTextField_Empty_LastName.getText(); 
              String expertise = jTextField_Expertise.getText(); 
                 String about = jTextField_About.getText(); 
        
        
        
        //check if the textfield is empty
        if(fname.isEmpty()){
                
           jLabel_EnterFname.setVisible(true);
            
        }else if(lname.isEmpty()){
                
         jLabel_EnterLname.setVisible(true);
            
        }  
           else{  //if the textfield is not empty        
                
           
         author.addAuthor(fname,lname,expertise,about);
            
            //refresh the jtable Genres 
           // populateJtableWIthGenres();
        
            //clear text form the textfields
            jTextField_ID.setText(" ");
            jTextField_Empty_Firstname.setText(" ");
            
    }
        
    }//GEN-LAST:event_jButton_AddActionPerformed

    
    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        
        
        //edit the selected author
        String fname = jTextField_Empty_Firstname.getText();    
           String lname = jTextField_Empty_LastName.getText();    
              String expertise  = jTextField_Expertise.getText();    
                  String about = jTextField_About.getText();
           
           
         //check if the textfield is empty
         
        //check if the textfield is empty
        if(fname.isEmpty()){
                
           jLabel_EnterFname.setVisible(true);
            
        }else if(lname.isEmpty()){
                
         jLabel_EnterLname.setVisible(true);
            
        }  
        {  //if the textfield is not empty        
         
            try{
                
            int id = Integer.parseInt(jTextField_ID.getText());
           author.editAuthor(id,fname,lname,expertise,about);
            
            // populateJtableWIthGenres();
             
            }
            
          catch(NumberFormatException ex){
              JOptionPane.showMessageDialog(null, "Invalid Author ID - " + ex.getMessage(),"error",0);
              
              
          }
            
        }    
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
       
        
     
       
          // delete the selected author
        try{
             int id = Integer.parseInt(jTextField_ID.getText());
            author.removeAuthor(id);
            // populateJtableWIthGenres();
              
             //clear text form
           
             jTextField_ID.setText("");
                jTextField_Empty_Firstname.setText( " ");
                   jTextField_Empty_LastName.setText( " ");
                      jTextField_Expertise.setText(" ");     
                          jTextField_About.setText(" ");    
            }
          catch(NumberFormatException ex){
              JOptionPane.showMessageDialog(null, "Invalid Author ID - " + ex.getMessage(),"error",0);
          }
           
      
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTable_GenresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_GenresMouseClicked

        //display the selected genre
        //get the selected row index
        int index = jTable_Genres.getSelectedRow();
        
        String id = jTable_Genres.getValueAt(index ,0).toString();
        String name = jTable_Genres.getValueAt(index,1).toString();
      
        //show data in textfield
        jTextField_ID.setText(id);
        jTextField_Empty_Firstname.setText(name);
    }//GEN-LAST:event_jTable_GenresMouseClicked

    //create a function to populate the jtable with genres
   public void populateJtableWIthGenres() {
       
       /*
       
    ArrayList<Genre> genreList = genre.genreList();
        
    // JTable columns
    String[] colNames = {"ID", "NAME"};
        
    // Rows
    Object[][] rows = new Object[genreList.size()][colNames.length];
        
    for (int i = 0; i < genreList.size(); i++) {
        
        rows[i][0] = genreList.get(i).getId();
        rows[i][1] = genreList.get(i).getName();
       
    }
       
    DefaultTableModel model = new DefaultTableModel(rows, colNames);
    jTable_Genres.setModel(model);
  */
}
    
    private void jLabel_EnterFnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EnterFnameMouseClicked
        // hide this jlabel on click
        jLabel_EnterFname.setVisible(false);
    }//GEN-LAST:event_jLabel_EnterFnameMouseClicked

    private void jTextField_Empty_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Empty_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Empty_LastNameActionPerformed

    private void jTextField_ExpertiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ExpertiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ExpertiseActionPerformed

    private void jTextField_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AboutActionPerformed

    private void jLabel_EnterLnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EnterLnameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EnterLnameMouseClicked

  
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    
                    
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAuthorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_EnterFname;
    private javax.swing.JLabel jLabel_EnterLname;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_MGF;
    private javax.swing.JPanel jPanel_Platform_C;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable_Genres;
    private javax.swing.JTextField jTextField_About;
    private javax.swing.JTextField jTextField_Empty_Firstname;
    private javax.swing.JTextField jTextField_Empty_LastName;
    private javax.swing.JTextField jTextField_Expertise;
    private javax.swing.JTextField jTextField_ID;
    // End of variables declaration//GEN-END:variables
}
